version: '3.8'

services:
  app:
    build:
      context: .  # Dockerfile'ın bulunduğu dizin
      dockerfile: Dockerfile  # Dockerfile'ınızın adı
    volumes:
      - .:/var/www  # Proje dosyalarını container'a kopyalar
    ports:
      - "8000:80"  # Laravel uygulamanızın 80 portunu host'a yönlendirin
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=ipenv
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - db  # MySQL servisi önce başlatılır, sonra app başlatılır

  db:
    image: mysql:8.0  # MySQL 8.0 imajını kullan
    environment:
      MYSQL_DATABASE: ipenv
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"  # MySQL container'ını host'a yönlendir

  nginx:
    image: nginx:latest  # Nginx imajını kullan
    volumes:
      - .:/var/www  # Proje dosyalarını Nginx container'ına kopyalar
      - .\nginx.conf:/etc/nginx/conf.d\default.conf  # Nginx konfigürasyonunu container'a ekler
    ports:
      - "80:80"  # Nginx 80 portunu dışa açar
    depends_on:
      - app  # Nginx servisi, Laravel uygulamanız başlatıldıktan sonra çalışır
